version: 2
defaults: &defaults
  machine:
    image: circleci/classic:edge

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/ci

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: ./scripts/ci-publish.sh

workflows:
  version: 2
  default-workflow:
    jobs:
      - test

      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v.*source/
            branches:
              ignore: /.*/
